# Generated by Django 5.1.2 on 2024-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='discounted_price',
            field=models.IntegerField(blank=True),
        ),
    ]
